apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::574457274275:role/eksctl-eks-cluster-nodegroup-ng-1-NodeInstanceRole-1UKL4Z9LWBAWF
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::574457274275:user/k8s-cluster-admin
      username: k8s-cluster-admin
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: '2021-06-09T16:44:01Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1738'
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 54d9af33-c6b7-4cdd-b45f-5142eb29ef59
