apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::574457274275:role/eksctl-EKS-cluster-aws-nodegroup-NodeInstanceRole-1L9Y4VKKTJXMZ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::574457274275:user/k8s-cluster-admin
      username: k8s-cluster-admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::574457274275:user/k8s-cluster-prod-viewer
      username: k8s-cluster-prod-viewer
      groups:
        - prod-viewer-role
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::574457274275:role/eksctl-EKS-cluster-aws-nodegroup-NodeInstanceRole-1L9Y4VKKTJXMZ\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"- userarn: arn:aws:iam::574457274275:user/k8s-cluster-admin\n  username: k8s-cluster-admin\n  groups:\n    - system:masters\n- userarn: arn:aws:iam::574457274275:user/k8s-cluster-prod-viewer\n  username: k8s-cluster-prod-viewer\n  groups:\n    - prod-viewer-role\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2021-05-30T23:37:27Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1453","selfLink":"/api/v1/namespaces/kube-system/configmaps/aws-auth","uid":"a6bca8c0-e915-48e1-baf1-e9a007bddc48"}}
  creationTimestamp: "2021-05-30T23:37:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4035"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a6bca8c0-e915-48e1-baf1-e9a007bddc48
