kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-viewer-binding
  namespace: production
subjects:
  - kind: User
    name: k8s-cluster-prod-viewer
    apiGroup: ''
roleRef:
  kind: Role
  name: prod-viewer-role
  apiGroup: ''
